### ISSUE TITLE
Mie_Protector Download Link does not work

### ISSUE THREAD

**Issue by NiclasQueen** [FaigerSYS/MapImageEngine#12]
pls fix

**Comment by NiclasQueen** [comment]
[Server thread/CRITICAL]: ErrorException: "Declaration of BlockHorizons\BlockPets\pets\BasePet::attack($damage, pocketmine\event\entity\EntityDamageEvent $source) should be compatible with pocketmine\entity\Living::attack(pocketmine\event\entity\EntityDamageEvent $source)" (EXCEPTION) in "blockpets-masterfromphar/src/BlockHorizons/BlockPets/pets/BasePet" at line 33

**Comment by NiclasQueen** [comment]
[Server thread/CRITICAL]: Error: "Access to undeclared static property: pocketmine\item\Item::$list" (EXCEPTION) in "Mie.phar/src/FaigerSYS/MapImageEngine/MapImageEngine" at line 80

**Comment by FaigerSYS** [comment]
Fixed
