### ISSUE TITLE
Both the Website and the Plugin are not working

### ISSUE THREAD

**Issue by MistakingManx** [FaigerSYS/MapImageEngine#13]
**OS:** Linux _Online pure PMMP host_
**Server:** PocketMine-MP   PMMP
**IP and Port in case you want to test yourself:** bpserverz.mcraft.pro 27678
**Problem:**
  _Plugin:_ It says it is Successful but then doesn't work
  _Website:_ Unknown Error with every image i upload

**Comment by FaigerSYS** [comment]
Plugin: what exactly doesn't work?
Website: try to use another browser

**Comment by Crypt97** [comment]
website link?

**Comment by NiclasQueen** [comment]
http://mie-converter.ml/?i=1

**Comment by FaigerSYS** [comment]
Website will be fixed soon

**Comment by FaigerSYS** [comment]
Fixed. Try to convert your image
