### ISSUE TITLE
Images dosnt apppair 

### ISSUE THREAD

**Issue by armagadon159753** [FaigerSYS/MapImageEngine#16]
![screenshot_2017-09-28-20-13-16](https://user-images.githubusercontent.com/25569806/30983218-08760f96-a48a-11e7-8a32-a53bda699e92.png)

**Comment by FreakingDev** [comment]
did you use the latest update ?

**Comment by armagadon159753** [comment]
@FreakingDev yes last .phar form poggit

**Comment by FaigerSYS** [comment]
Can you show me /plugins command output?

**Comment by armagadon159753** [comment]
Ooh on poggit the last .phar is 1.0.9
I will try with 1.10.0 and tell if m'y issu are solved
![_20170929_161905](https://user-images.githubusercontent.com/25569806/31020062-273b8ab6-a532-11e7-89a0-d394beb5acd1.JPG)

**Comment by FaigerSYS** [comment]
How it works now?

**Comment by armagadon159753** [comment]
Yes its work fine i can close this issu now thx for all
