### ISSUE TITLE
How do I resolve this error?

### ISSUE THREAD

**Issue by yunseo2723** [FaigerSYS/MapImageEngine#26]
![zz](https://user-images.githubusercontent.com/25340054/33870556-af57b592-df51-11e7-97f7-eec9d539dec6.PNG)

Please fix it.

**Comment by FienixEC** [comment]
what software are u using?

**Comment by yunseo2723** [comment]
hmmm...Where can I find the software? Well ... Are you saying Windows 10 ..? I'm using 64-bit Windows 10. Linux.

**Comment by yunseo2723** [comment]
Aha! I am using PMMP.

**Comment by FienixEC** [comment]
pkay, and which version of MapImageEngine are you using?

**Comment by yunseo2723** [comment]
Well ... I want to use the ALPHA10 version which is error free and I was using it by updating the plugin that came up here with ALPHA10

**Comment by yunseo2723** [comment]
So, is it possible to upload this plugin to ALPHA10 ...?

**Comment by FienixEC** [comment]
yes, do u have kik by chance?

**Comment by FienixEC** [comment]
or i can create a fork later with the fix

**Comment by FienixEC** [comment]
Fixed on my fork

**Comment by Antisa14200** [comment]
@FienixEC After that, while trying to put image, i get this error

[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'MapImageEngine v1.1-ALPHA1': Call to undefined method FaigerSYS\MapImageEngine\storage\ImageStorage::getMapId() on FaigerSYS\MapImageEngine\command\MapImageEngineCommand
[12:59:12] [Server thread/CRITICAL]: Error: "Call to undefined method FaigerSYS\MapImageEngine\storage\ImageStorage::getMapId()" (EXCEPTION) in "MIE-master/src/FaigerSYS/MapImageEngine/item/FilledMap" at line 63

How do I resolve it?

**Comment by FienixEC** [comment]
@yunseo2723 in /src/FaigerSYS/MapImageEngine/item/FilledMap file, replace all $tag with  $tags
lastly in same file look for:
public function setNamedTag(CompoundTag $tags) & public function setCompoundTag($tags)

and add:
 : item
 after $tags)

and thats all, should work after

**Comment by yunseo2723** [comment]
Thank you so much!~ I try it

**Comment by FienixEC** [comment]
@yunseo2723  if not, heres the master folder which acts as a .phar file that i use on my server, 100% working with no errors, jus download and unzip to ur plugins folder and restart ur server:

http://www.mediafire.com/file/cuo1ujrtn4c146e/MapImageEngine-master.zip

**Comment by yunseo2723** [comment]
I would like to insert an item frame protection plug-in in order to prevent the picture in the item frame from being dropped after applying this plug-in. Where can I find the plug-in?

**Comment by Antisa14200** [comment]
https://github.com/FaigerSYS/MapImageEngine/tree/master/MIE_Protector I guess you're searching for this
