### ISSUE TITLE
How do I resolve this error?

### ISSUE THREAD

**Issue by Antisa14200** [FaigerSYS/MapImageEngine#27]
[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'MapImageEngine v1.1-ALPHA1': Call to undefined method FaigerSYS\MapImageEngine\storage\ImageStorage::getMapId() on FaigerSYS\MapImageEngine\command\MapImageEngineCommand
[12:59:12] [Server thread/CRITICAL]: Error: "Call to undefined method FaigerSYS\MapImageEngine\storage\ImageStorage::getMapId()" (EXCEPTION) in "MIE-master/src/FaigerSYS/MapImageEngine/item/FilledMap" at line 63

ALPHA10 on Windows 10 64 bit

**Comment by FienixEC** [comment]
@Antisa14200  fixed at https://github.com/FienixEC/MapImageEngine/commit/ca717396c2f8041aed30251f38704b1ebaddb0a2

**Comment by Antisa14200** [comment]
Even with this version above, while trying to place pics in a frame on a server, I keep getting: 

[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'MapImageEngine v1.1-ALPHA1': Call to undefined method FaigerSYS\MapImageEngine\storage\ImageStorage::getMapId() on FaigerSYS\MapImageEngine\command\MapImageEngineCommand
[09:16:36] [Server thread/CRITICAL]: Error: "Call to undefined method FaigerSYS\MapImageEngine\storage\ImageStorage::getMapId()" (EXCEPTION) in "MapImageEngine-master/src/FaigerSYS/MapImageEngine/item/FilledMap" at line 63

So idk what to do

**Comment by FienixEC** [comment]
copy and paste my code

**Comment by Antisa14200** [comment]
@FienixEC I did downloaded a version from your fork and same error shows

**Comment by Antisa14200** [comment]
@FienixEC And code is the one you updated and same error shows still

**Comment by Antisa14200** [comment]
Anyone able to help?

**Comment by FienixEC** [comment]
@Antisa14200  if u have a way i can send u my exact master folder which works, i can do that, not sure why u are getting that error, my fork is the exact one im using with 0 error, but again i can send you the exact master folder directly off of my main server, let me know if u have kik or something

**Comment by Antisa14200** [comment]
You have twitter?

**Comment by FienixEC** [comment]
i dont think i can send files through twitter, let me jus upload the zipped master folder to my mediafire and jus send u the link

**Comment by Antisa14200** [comment]
Upload the files i exactly need tho

**Comment by FienixEC** [comment]
http://www.mediafire.com/file/cuo1ujrtn4c146e/MapImageEngine-master.zip

download and unzip this zip into ur plugins folder. restart ur server and should work

**Comment by FienixEC** [comment]
@Antisa14200  if u need a .phar file let me know

**Comment by Antisa14200** [comment]
This one worked, thank you!

**Comment by FienixEC** [comment]
@Antisa14200 FINALLY lmaoo, im gladd, i knew i fixed itt haha, enjoy!!! :)

**Comment by Antisa14200** [comment]
It's weird then if you said it's the same file, how is the one you just send me working while the forked one here shows that error

**Comment by FienixEC** [comment]
@antisa14200 i have the same issue im dealing with with someone else. i sent them the code changes on other files amd sent u the diff changes in the code. thought it was the same issue. it was my bad on info

**Comment by Antisa14200** [comment]
Oh, no problem
Good thing it works anyway

**Comment by Antisa14200** [comment]
Add me on twitter if you have it tho: @ante0321

**Comment by FienixEC** [comment]
@Antisa14200 u should get kik

**Comment by Antisa14200** [comment]
I had it
And deleted it
😂

**Comment by FienixEC** [comment]
@Antisa14200 lmaoooo u should get it againnn

**Comment by Antisa14200** [comment]
Whats your user on kik?

**Comment by FienixEC** [comment]
Makaveli_8
