### ISSUE TITLE
MapImageEngine broken on version 3 API10

### ISSUE THREAD

**Issue by artulloss** [FaigerSYS/MapImageEngine#30]
Log:
04.02 03:49:32 [Server] Server thread/INFO Enabling MapImageEngine v1.1-ALPHA2
04.02 03:49:32 [Server] Server thread/INFO MapImageEngine enabling...
04.02 03:49:32 [Server] Server thread/INFO Notice #1: find the instructions in the plugin folder
04.02 03:49:32 [Server] Server thread/INFO Notice #2: after installing new images or updating plugin enabling may take longer, but then it will be as usual
04.02 03:49:32 [Server] Server thread/INFO Notice #3: after installing MapImageEngine v1.1 you must place all your previously placed images again
04.02 03:49:32 [Server] Server thread/CRITICAL Error: "Class 'FaigerSYS\MapImageEngine\item\FilledMap' not found" (EXCEPTION) in "MapImageEngine/src/FaigerSYS/MapImageEngine/MapImageEngine" at line 105
04.02 03:49:32 [Server] Server thread/DEBUG #0 MapImageEngine/src/FaigerSYS/MapImageEngine/MapImageEngine(67): FaigerSYS\MapImageEngine\MapImageEngine->registerItems()
04.02 03:49:32 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginBase(90): FaigerSYS\MapImageEngine\MapImageEngine->onEnable()
04.02 03:49:32 [Server] Server thread/DEBUG #2 PocketMine-DevTools.phar/src/FolderPluginLoader/FolderPluginLoader(127): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
04.02 03:49:32 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(610): FolderPluginLoader\FolderPluginLoader->enablePlugin(FaigerSYS\MapImageEngine\MapImageEngine object)
04.02 03:49:32 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1955): pocketmine\plugin\PluginManager->enablePlugin(FaigerSYS\MapImageEngine\MapImageEngine object)
04.02 03:49:32 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1941): pocketmine\Server->enablePlugin(FaigerSYS\MapImageEngine\MapImageEngine object)
04.02 03:49:32 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1735): pocketmine\Server->enablePlugins(integer 1)
04.02 03:49:32 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
04.02 03:49:32 [Server] Server thread/DEBUG #8 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
04.02 03:49:32 [Server] Server thread/INFO Disabling MapImageEngine v1.1-ALPHA2

**Comment by FaigerSYS** [comment]
Your plugin is corrupted, just download it again
