### ISSUE TITLE
Please support Altay!!

### ISSUE THREAD

**Issue by OtorisanVardo** [FaigerSYS/MapImageEngine#31]
My server software is [Altay](https://github.com/TuranicTeam/Altay). 
below error happened the timing which player join.

help me...!!

```
RuntimeException: "Dynamic field access on pocketmine\nbt\tag\CompoundTag is no longer supported" (EXCEPTION) in "vendor/pocketmine/pocketmine-nbt/src/tag/NoDynamicFieldsTrait" at line 29
```

**Comment by xinghao2003** [comment]
I have this issue on latest PocketMine-MP too

**Comment by SleepSpace9** [comment]
Feel free to test my PR (https://github.com/FaigerSYS/MapImageEngine/pull/32) which should fix this issue.

Link to phar is here:
https://raw.githubusercontent.com/SleepSpace9/MapImageEngine/pmmp-alpha11/MapImageEngine/releases/MapImageEngine_v1.0.11.phar

**Comment by OtorisanVardo** [comment]
Thanks!
i try to use this!
