### ISSUE TITLE
Сделай уже поддержку всех новых ядер, пожалуйста

### ISSUE THREAD

**Issue by ProCOmpTEAM** [FaigerSYS/MapImageEngine#33]

**Comment by ProCOmpTEAM** [comment]
@FaigerSYS все очень ждут

**Comment by ProCOmpTEAM** [comment]
![default](https://user-images.githubusercontent.com/24737193/36778000-851c2a2a-1c7c-11e8-99f1-ec826ce03fbe.png)

**Comment by SleepSpace9** [comment]
This should be fixed in my PR (https://github.com/FaigerSYS/MapImageEngine/pull/32), try it if you like.

**Comment by ProCOmpTEAM** [comment]
@SleepSpace9 thank you very much, is workering!
but sometimes i get some messages
![default](https://user-images.githubusercontent.com/24737193/36932146-faa77c76-1ed5-11e8-8c04-0598bca1a2b6.png)
