### ISSUE TITLE
DO NOT USE THIS

### ISSUE THREAD

**Issue by artulloss** [FaigerSYS/MapImageEngine#38]
Every roughly 10 minutes this plugin drops your TPS to 0 and strain to 100%
This uses complex math on the main thread in order to calculate the colors.
DO NOT USE

**Comment by FaigerSYS** [comment]
Ummm, it calculates everything when the plugin is loaded. I don't know what's going on with your TPS, but my plugin has nothing to do with it.

**Comment by artulloss** [comment]
@FaigerSYS yea, I was going to close this, it's odd. I removed it and it vanished on my test server, and the test server and the main server have the same plugins.
