### ISSUE TITLE
Mieprotect

### ISSUE THREAD

**Issue by optimusprime338** [FaigerSYS/MapImageEngine#4]
Mieprotect dont work!

**Comment by FaigerSYS** [comment]
What do you mean? Any error happened? Can you explain?

**Comment by optimusprime338** [comment]
No errors it just don't work..am I supposed to do anything to protect???? I have installed plugin etc

**Comment by FaigerSYS** [comment]
What exactly are you doing? How can this be reproduced?

**Comment by optimusprime338** [comment]
Using Genesispro + mie + mieprotector
/mie place xxx
Player is able to remove image(map)

**Comment by FaigerSYS** [comment]
OPs can destroy images. Check player's permissions, and try again. If everything OK, update your GenisysPro to latest version
