### ISSUE TITLE
New version 1.5, i use this plugin. What is this error?

### ISSUE THREAD

**Issue by OtorisanVardo** [FaigerSYS/MapImageEngine#43]
Fatal error: Declaration of FaigerSYS\MapImageEngine\packet\CustomClientboundMapItemDataPacket::decodePayload() must be compatible with pocketmine\network\mcpe\protocol\DataPacket::decodePayload(): void in /home/minpe/plugins/MapImageEngine/src/FaigerSYS/MapImageEngine/packet/CustomClientboundMapItemDataPacket.php on line 224

On server starting, This error happened.
Please fix it ><

**Comment by Nerahikada** [comment]
MapImageEngine/packet/CustomClientboundMapItemDatapacket.php on line 83
```
protected function decodePayload() {
```
change to
```
protected function decodePayload() : void {
```

**Comment by OtorisanVardo** [comment]
Thank you very much!
