### ISSUE TITLE
22:25:16 CRITICAL > Error: "Class 'pocketmine\network\mcpe\protocol\BatchPacket' not found" (EXCEPTION) in "plugins/MapImageEngine/src/FaigerSYS/MapImageEngine/storage/ImageStorage" at line 120

### ISSUE THREAD

**Issue by SuperAdam47** [FaigerSYS/MapImageEngine#45]
22:25:16 CRITICAL > Error: "Class 'pocketmine\network\mcpe\protocol\BatchPacket' not found" (EXCEPTION) in "plugins/MapImageEngine/src/FaigerSYS/MapImageEngine/storage/ImageStorage" at line 120

**Comment by FaigerSYS** [comment]
MIE hasn't real support of API 4.0.0 because it's still in development. Try to use PocketMine-MP releases with API version 3.2 or older
