### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Akuroma** [FaigerSYS/MapImageEngine#48]
`Fatal error: Declaration of FaigerSYS\MapImageEngine\packet\CustomClientboundMapItemDataPacket::handle(pocketmine\network\mcpe\NetworkSession $session): bool must be compatible with pocketmine\network\mcpe\protocol\DataPacket::handle(pocketmine\network\mcpe\handler\SessionHandler $handler): bool in /home/gs/gs/data/servers/8687812/plugins/MapImageEngine-master/src/FaigerSYS/MapImageEngine/packet/CustomClientboundMapItemDataPacket.php on line 224`

Happens with the latest PocketMine-MP version.

**Comment by FaigerSYS** [comment]
https://github.com/FaigerSYS/MapImageEngine/issues/45#issuecomment-408017261
