### ISSUE TITLE
http://mie-converter.ml Site Down.

### ISSUE THREAD

**Issue by FienixEC** [FaigerSYS/MapImageEngine#9]
http://mie-converter.ml Site Down. Can you pls fix?

**Comment by FaigerSYS** [comment]
It works fine

**Comment by Eren3219X** [comment]
Site closed ?

**Comment by FadhelGamer** [comment]
The plugin mie_convert is not work on my server and the web is not work.... can you fix it?

**Comment by FaigerSYS** [comment]
@FadhelGamer , at first please provide more information. What exactly not works?

**Comment by FadhelGamer** [comment]
Also mie protect is work with map image work but the mie convert plugin is not work and idont know how i can add image my friend he have the plugin with server and is works on his server and not work on my server and the console didnt send me whats the plugin problem.

**Comment by SuperAdam47** [comment]
@FaigerSYS 
![image](https://user-images.githubusercontent.com/16169771/43598525-8e644a82-968d-11e8-833b-6a251d3ef236.png)

**Comment by SuperAdam47** [comment]
use vpn

**Comment by FadhelGamer** [comment]
Its not work for me the website in my city....

**Comment by tanercelik** [comment]
Please fix site i use vnp not working

**Comment by FaigerSYS** [comment]
@tanercelik , you can always use plugin to convert images

**Comment by GamerDaniel3000** [comment]
For me it is down

**Comment by Mer0naS** [comment]
> Работает нормально

Этот сайт работает, но не так как надо. Он должен конвертировать в .mie а не в .miei

**Comment by Mer0naS** [comment]
Если плагин может конвентировать, то как?
